### ISSUE TITLE
delete from_csv not working

### ISSUE THREAD

**Issue by cllns** [spiceee/i_delete_my_tweets#7]
I downloaded an archive and was able to convert it to CSV, but when running  `i_delete_my_tweets delete from_csv`, I got an error.

With Ruby 3.1.0:

```bash
/Users/sean/.rubies/ruby-3.1.2/lib/ruby/3.1.0/csv/parser.rb:618:in `gets': Is a directory @ io_fillbuf - fd:9 ./ (Errno::EISDIR)
	from /Users/sean/.rubies/ruby-3.1.2/lib/ruby/3.1.0/csv/parser.rb:618:in `resolve_row_separator'
	from /Users/sean/.rubies/ruby-3.1.2/lib/ruby/3.1.0/csv/parser.rb:499:in `prepare_separators'
	from /Users/sean/.rubies/ruby-3.1.2/lib/ruby/3.1.0/csv/parser.rb:364:in `prepare'
	from /Users/sean/.rubies/ruby-3.1.2/lib/ruby/3.1.0/csv/parser.rb:265:in `initialize'
	from /Users/sean/.rubies/ruby-3.1.2/lib/ruby/3.1.0/csv.rb:2635:in `new'
	from /Users/sean/.rubies/ruby-3.1.2/lib/ruby/3.1.0/csv.rb:2635:in `parser'
	from /Users/sean/.rubies/ruby-3.1.2/lib/ruby/3.1.0/csv.rb:2644:in `parser_enumerator'
	from /Users/sean/.rubies/ruby-3.1.2/lib/ruby/3.1.0/csv.rb:2365:in `each'
	from /Users/sean/.rubies/ruby-3.1.2/lib/ruby/3.1.0/csv.rb:1218:in `block in foreach'
	from /Users/sean/.rubies/ruby-3.1.2/lib/ruby/3.1.0/csv.rb:1450:in `open'
	from /Users/sean/.rubies/ruby-3.1.2/lib/ruby/3.1.0/csv.rb:1217:in `foreach'
	from /Users/sean/development/i_delete_my_tweets/lib/i_delete_my_tweets/api.rb:32:in `traverse_csv!'
	from /Users/sean/development/i_delete_my_tweets/lib/i_delete_my_tweets/cli.rb:58:in `from_csv'
	from /Users/sean/.gem/ruby/3.1.2/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/sean/.gem/ruby/3.1.2/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/sean/.gem/ruby/3.1.2/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/sean/.gem/ruby/3.1.2/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
	from /Users/sean/.gem/ruby/3.1.2/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
	from /Users/sean/.gem/ruby/3.1.2/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/sean/.gem/ruby/3.1.2/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/sean/.gem/ruby/3.1.2/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/sean/.gem/ruby/3.1.2/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
```

With Ruby 2.7.6:

```bash
Traceback (most recent call last):
	23: from bin/i_delete_my_tweets:18:in `<main>'
	22: from /Users/sean/.gem/ruby/2.7.6/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	21: from /Users/sean/.gem/ruby/2.7.6/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	20: from /Users/sean/.gem/ruby/2.7.6/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	19: from /Users/sean/.gem/ruby/2.7.6/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	18: from /Users/sean/.gem/ruby/2.7.6/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
	17: from /Users/sean/.gem/ruby/2.7.6/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
	16: from /Users/sean/.gem/ruby/2.7.6/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	15: from /Users/sean/.gem/ruby/2.7.6/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	14: from /Users/sean/.gem/ruby/2.7.6/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	13: from /Users/sean/development/i_delete_my_tweets/lib/i_delete_my_tweets/cli.rb:58:in `from_csv'
	12: from /Users/sean/development/i_delete_my_tweets/lib/i_delete_my_tweets/api.rb:32:in `traverse_csv!'
	11: from /Users/sean/.rubies/ruby-2.7.6/lib/ruby/2.7.0/csv.rb:510:in `foreach'
	10: from /Users/sean/.rubies/ruby-2.7.6/lib/ruby/2.7.0/csv.rb:658:in `open'
	 9: from /Users/sean/.rubies/ruby-2.7.6/lib/ruby/2.7.0/csv.rb:511:in `block in foreach'
	 8: from /Users/sean/.rubies/ruby-2.7.6/lib/ruby/2.7.0/csv.rb:1280:in `each'
	 7: from /Users/sean/.rubies/ruby-2.7.6/lib/ruby/2.7.0/csv.rb:1478:in `parser_enumerator'
	 6: from /Users/sean/.rubies/ruby-2.7.6/lib/ruby/2.7.0/csv.rb:1469:in `parser'
	 5: from /Users/sean/.rubies/ruby-2.7.6/lib/ruby/2.7.0/csv.rb:1469:in `new'
	 4: from /Users/sean/.rubies/ruby-2.7.6/lib/ruby/2.7.0/csv/parser.rb:263:in `initialize'
	 3: from /Users/sean/.rubies/ruby-2.7.6/lib/ruby/2.7.0/csv/parser.rb:362:in `prepare'
	 2: from /Users/sean/.rubies/ruby-2.7.6/lib/ruby/2.7.0/csv/parser.rb:492:in `prepare_separators'
	 1: from /Users/sean/.rubies/ruby-2.7.6/lib/ruby/2.7.0/csv/parser.rb:592:in `resolve_row_separator'
/Users/sean/.rubies/ruby-2.7.6/lib/ruby/2.7.0/csv/parser.rb:592:in `gets': Is a directory @ io_fillbuf - fd:9 ./ (Errno::EISDIR)
```

This does *not* appear to be anything specific to my CSV file: it happens when I reduce the converted_tweets.csv file to just the very first one (and also remove them altogether).

I'm just running it in the other mode instead.

**Comment by spiceee** [comment]
@cllns Were you able to fix this? Should I try to repro?

**Comment by cllns** [comment]
No I wasn't able to fix it, I just used the other method

**Comment by spiceee** [comment]
Thanks, will take a 👀
